// CRUD for the proceedings you track + listing detected new filings.
//   GET    /api/watchlist                                              → { watched, findings }
//   POST   /api/watchlist  { applicationNumber, label, recipients }    → add + baseline sync  [admin]
//   POST   /api/watchlist  { action: "updateRecipients", applicationNumber, recipients }      [admin]
//   POST   /api/watchlist  { action: "acknowledge" [, applicationNumber, documentIdentifier] } [admin]
//   DELETE /api/watchlist?applicationNumber=...                        → stop tracking        [admin]
//
// "[admin]" actions require the X-Admin-Password header to match the
// ADMIN_PASSWORD env var. Auth fails CLOSED: with no ADMIN_PASSWORD configured,
// admin actions are refused (SEC-1). Unsubscribe-from-alerts is public but
// token-gated (HMAC per recipient, SEC-2) and rate-limited.

import {
  listWatched, addWatched, removeWatched, setRecipients, removeRecipientFromAllWatched,
  listFindings, acknowledgeFindings, acknowledgeFinding, syncApplication,
  getStatusSnapshot, listReexamSubscribers,
} from '../lib/db.js';
import { isAdmin, unsubTokenOk, clientErrorDetail } from '../lib/secure.js';
import { rateLimited } from '../lib/ratelimit.js';

// Clean a recipient string into a normalized comma-separated list (or null).
function normalizeRecipients(s) {
  const list = String(s || '').split(/[,;]/).map((x) => x.trim()).filter(Boolean);
  return list.length ? list.join(', ') : null;
}

function esc(s) { return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

// Minimal standalone page for the email-link unsubscribe confirm/result.
function unsubPage(title, inner) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${esc(title)}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f0f4f8;color:#2d3748;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;padding:24px}.box{background:#fff;border-radius:10px;box-shadow:0 1px 4px rgba(0,0,0,0.1);padding:32px 28px;max-width:460px;text-align:center}h1{font-size:1.25rem;color:#1a3a6b;margin:0 0 10px}p{font-size:0.95rem;line-height:1.5;margin:0 0 18px}.btn{display:inline-block;background:#1a3a6b;color:#fff;border:none;cursor:pointer;text-decoration:none;font-weight:600;font-size:0.95rem;padding:10px 18px;border-radius:8px}.btn:hover{background:#15305a}.btn.muted{background:#e2e8f0;color:#1a3a6b;margin-left:8px}</style></head><body><div class="box"><h1>${esc(title)}</h1>${inner}</div></body></html>`;
}

// Recipient emails are PII — strip them for non-admin callers so the public
// /api/watchlist response can't be scraped for addresses. Admins (valid
// X-Admin-Password) still get them, which powers the recipient-edit flow.
function maskWatched(watched, req) {
  if (isAdmin(req)) return watched;
  return watched.map((w) => { const { recipients, ...rest } = w; return rest; });
}

export default async function handler(req, res) {
  try {
    if (req.method === 'GET') {
      // Unsubscribe-from-all-tracked-proceedings (from an alert email's link):
      // GET shows a confirmation page only — no state change — so email security
      // scanners that pre-fetch the link don't unsubscribe anyone. Removal happens
      // on the POST below.
      if (req.query && req.query.unsubscribeAlerts) {
        const email = String(req.query.unsubscribeAlerts);
        const token = String(req.query.t || '');
        res.setHeader('Content-Type', 'text/html; charset=utf-8');
        // Token-gated (SEC-2): only links generated by our alert emails carry a
        // valid per-recipient token, so a raw email address can't be unsubscribed
        // by anyone who merely knows it.
        if (!unsubTokenOk(email, token)) {
          res.status(400).send(unsubPage('Invalid link',
            `<p>This unsubscribe link is invalid or has expired. Please use the link from a recent alert email.</p><a class="btn muted" href="/uspto-search">Back to the app</a>`));
          return;
        }
        res.status(200).send(unsubPage('Unsubscribe',
          `<p>Stop sending <strong>${esc(email)}</strong> new-filing alerts for <strong>all</strong> tracked proceedings?</p>
           <form method="POST" action="/api/watchlist" style="margin:0">
             <input type="hidden" name="action" value="unsubscribeAlerts" />
             <input type="hidden" name="email" value="${esc(email)}" />
             <input type="hidden" name="t" value="${esc(token)}" />
             <button class="btn" type="submit">Unsubscribe</button>
             <a class="btn muted" href="/uspto-search">Cancel</a>
           </form>`));
        return;
      }
      // Admin-only operational snapshot for the /status page.
      if (req.query && req.query.status) {
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        res.setHeader('Cache-Control', 'no-store');
        res.status(200).json({ status: await getStatusSnapshot() });
        return;
      }
      // Admin-only: the daily-email subscriber list (emails only, no tokens).
      if (req.query && req.query.subscribers) {
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        res.setHeader('Cache-Control', 'no-store');
        const subs = await listReexamSubscribers();
        res.status(200).json({ subscribers: subs.map((s) => s.email), count: subs.length });
        return;
      }
      // Admin-only: tracked proceedings + the alert recipients for each.
      if (req.query && req.query.tracked) {
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        res.setHeader('Cache-Control', 'no-store');
        const watched = await listWatched();
        res.status(200).json({ tracked: watched.map((w) => ({ application_number: w.application_number, label: w.label, recipients: w.recipients, latest_date: w.latest_date })) });
        return;
      }
      const [watched, findings] = await Promise.all([listWatched(), listFindings()]);
      res.status(200).json({ watched: maskWatched(watched, req), findings });
      return;
    }

    if (req.method === 'POST') {
      let body = req.body;
      if (typeof body === 'string') {
        // JSON (on-site fetch) or x-www-form-urlencoded (the unsubscribe form / one-click).
        try { body = JSON.parse(body); }
        catch { body = Object.fromEntries(new URLSearchParams(body)); }
      }
      body = body || {};

      // Unsubscribe an email from ALL tracked proceedings. Public + self-service:
      // the on-site box (JSON), the email confirm-page form (urlencoded → HTML
      // result), or an RFC 8058 one-click POST (List-Unsubscribe=One-Click).
      const oneClick = body['List-Unsubscribe'] === 'One-Click';
      if (body.action === 'unsubscribeAlerts' || oneClick) {
        if (rateLimited(req, 10)) { res.status(429).json({ error: 'Too many requests. Please wait a minute and try again.' }); return; }
        const email = String(body.email || (req.query && req.query.unsubscribeAlerts) || '').trim();
        const token = String(body.t || (req.query && req.query.t) || '').trim();
        // Token-gated (SEC-2): reject unsubscribe attempts that don't carry the
        // per-recipient token from an alert email.
        if (!unsubTokenOk(email, token)) {
          const wantsHtmlErr = !oneClick && !String(req.headers['content-type'] || '').includes('application/json');
          if (wantsHtmlErr) {
            res.setHeader('Content-Type', 'text/html; charset=utf-8');
            res.status(400).send(unsubPage('Invalid link', `<p>This unsubscribe link is invalid or has expired. Please use the link from a recent alert email.</p><a class="btn muted" href="/uspto-search">Back to the app</a>`));
          } else {
            res.status(400).json({ error: 'Invalid or missing unsubscribe token.' });
          }
          return;
        }
        const removed = email ? await removeRecipientFromAllWatched(email) : 0;
        const wantsHtml = !oneClick && !String(req.headers['content-type'] || '').includes('application/json');
        if (wantsHtml) {
          res.setHeader('Content-Type', 'text/html; charset=utf-8');
          res.status(200).send(unsubPage(removed ? 'Unsubscribed' : 'Nothing to remove',
            removed
              ? `<p><strong>${esc(email)}</strong> was removed from ${removed} tracked proceeding${removed === 1 ? '' : 's'} and will no longer receive new-filing alerts.</p><a class="btn" href="/uspto-search">Back to the app</a>`
              : `<p>No tracked proceedings were sending alerts to <strong>${esc(email)}</strong> (it may already have been removed).</p><a class="btn" href="/uspto-search">Back to the app</a>`));
          return;
        }
        res.status(200).json({ ok: true, email, removed });
        return;
      }

      if (body.action === 'verifyAdmin') {
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        res.status(200).json({ ok: true });
        return;
      }

      if (body.action === 'acknowledge') {
        // Admin-gated (SEC-2): otherwise anyone could mark all findings read,
        // hiding new filings from the admin.
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        // Acknowledge a single finding if identified, otherwise all of them.
        if (body.applicationNumber && body.documentIdentifier) {
          await acknowledgeFinding(String(body.applicationNumber), String(body.documentIdentifier));
        } else {
          await acknowledgeFindings();
        }
        res.status(200).json({ ok: true });
        return;
      }

      if (body.action === 'updateRecipients') {
        if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
        const num = String(body.applicationNumber || '').replace(/[^0-9A-Za-z/]/g, '');
        if (!num) { res.status(400).json({ error: 'applicationNumber is required.' }); return; }
        await setRecipients(num, normalizeRecipients(body.recipients));
        const watched = await listWatched();
        res.status(200).json({ ok: true, watched: maskWatched(watched, req) });
        return;
      }

      // Add/track a proceeding — admin-gated (SEC-2): it accepts arbitrary
      // recipient emails that the alert cron then mails from our sender domain.
      if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
      const appNum = String(body.applicationNumber || '').replace(/[^0-9A-Za-z/]/g, '');
      if (!appNum) { res.status(400).json({ error: 'applicationNumber is required.' }); return; }

      const addResult = await addWatched(appNum, body.label, normalizeRecipients(body.recipients));

      // Baseline existing documents so only FUTURE filings count as "new". Only a
      // brand-new entry needs this; an already-tracked proceeding was baselined
      // when first added, so re-syncing on a plain email-list edit is redundant
      // (and would surface USPTO API errors for what isn't a tracking change).
      let baseline = null;
      if (!addResult.existed) {
        try { baseline = await syncApplication(appNum, false); }
        catch (e) { baseline = { error: String(e.message || e) }; }
      }

      const watched = await listWatched();
      res.status(200).json({ ok: true, watched: maskWatched(watched, req), baseline, existed: addResult.existed });
      return;
    }

    if (req.method === 'DELETE') {
      if (!isAdmin(req)) { res.status(401).json({ error: 'Incorrect or missing admin password.' }); return; }
      const appNum = String(req.query.applicationNumber || '').replace(/[^0-9A-Za-z/]/g, '');
      if (!appNum) { res.status(400).json({ error: 'applicationNumber is required.' }); return; }
      await removeWatched(appNum);
      res.status(200).json({ ok: true });
      return;
    }

    res.status(405).json({ error: 'Method not allowed.' });
  } catch (err) {
    res.status(500).json({ error: 'Watchlist operation failed.', detail: clientErrorDetail(err) });
  }
}
